from typing import Any, Callable, FrozenSet, Tuple, TypeVar, overload
from arc_types import (
    Boolean, Integer, IntegerTuple, Numerical,
    Grid, Object, Objects, Indices, IndicesSet, Patch, Element, Piece
)

_T = TypeVar('_T')
_U = TypeVar('_U')
_V = TypeVar('_V')

# Basic helpers used widely
def identity(x: Any) -> Any: ...

# Numerical ops with overloads to keep mypy happy
@overload
def add(a: Integer, b: Integer) -> Integer: ...
@overload
def add(a: IntegerTuple, b: IntegerTuple) -> IntegerTuple: ...
@overload
def add(a: Integer, b: IntegerTuple) -> IntegerTuple: ...
@overload
def add(a: IntegerTuple, b: Integer) -> IntegerTuple: ...

@overload
def subtract(a: Integer, b: Integer) -> Integer: ...
@overload
def subtract(a: IntegerTuple, b: IntegerTuple) -> IntegerTuple: ...
@overload
def subtract(a: Integer, b: IntegerTuple) -> IntegerTuple: ...
@overload
def subtract(a: IntegerTuple, b: Integer) -> IntegerTuple: ...

@overload
def multiply(a: Integer, b: Integer) -> Integer: ...
@overload
def multiply(a: IntegerTuple, b: IntegerTuple) -> IntegerTuple: ...
@overload
def multiply(a: Integer, b: IntegerTuple) -> IntegerTuple: ...
@overload
def multiply(a: IntegerTuple, b: Integer) -> IntegerTuple: ...

@overload
def divide(a: Integer, b: Integer) -> Integer: ...
@overload
def divide(a: IntegerTuple, b: IntegerTuple) -> IntegerTuple: ...
@overload
def divide(a: Integer, b: IntegerTuple) -> IntegerTuple: ...
@overload
def divide(a: IntegerTuple, b: Integer) -> IntegerTuple: ...

# Container ops
@overload
def apply(fn: Callable[[_T], _U], xs: FrozenSet[_T]) -> FrozenSet[_U]: ...
@overload
def apply(fn: Callable[[_T], _U], xs: Tuple[_T, ...]) -> Tuple[_U, ...]: ...

@overload
def merge(xss: FrozenSet[FrozenSet[_U]]) -> FrozenSet[_U]: ...
@overload
def merge(xss: Tuple[Tuple[_U, ...], ...]) -> Tuple[_U, ...]: ...

@overload
def mapply(fn: Callable[[_T], FrozenSet[_U]], xs: FrozenSet[_T]) -> FrozenSet[_U]: ...
@overload
def mapply(fn: Callable[[_T], Tuple[_U, ...]], xs: Tuple[_T, ...]) -> Tuple[_U, ...]: ...

def papply(fn: Callable[[_T, _U], _V], a: Tuple[_T, ...], b: Tuple[_U, ...]) -> Tuple[_V, ...]: ...

@overload
def mpapply(fn: Callable[[_T, _U], FrozenSet[_V]], a: Tuple[_T, ...], b: Tuple[_U, ...]) -> FrozenSet[_V]: ...
@overload
def mpapply(fn: Callable[[_T, _U], Tuple[_V, ...]], a: Tuple[_T, ...], b: Tuple[_U, ...]) -> Tuple[_V, ...]: ...

def prapply(fn: Callable[[_T, _U], _V], a: FrozenSet[_T], b: FrozenSet[_U]) -> FrozenSet[_V]: ...

# Selection
@overload
def first(xs: FrozenSet[_T]) -> _T: ...
@overload
def first(xs: Tuple[_T, ...]) -> _T: ...

@overload
def last(xs: FrozenSet[_T]) -> _T: ...
@overload
def last(xs: Tuple[_T, ...]) -> _T: ...

@overload
def extract(xs: FrozenSet[_T], pred: Callable[[_T], bool]) -> _T: ...
@overload
def extract(xs: Tuple[_T, ...], pred: Callable[[_T], bool]) -> _T: ...

# Branching
def branch(cond: bool, a: Any, b: Any) -> Any: ...

# Filters and ordering
@overload
def sizefilter(xs: FrozenSet[_T], n: int) -> FrozenSet[_T]: ...
@overload
def sizefilter(xs: Tuple[_T, ...], n: int) -> Tuple[_T, ...]: ...

@overload
def order(xs: FrozenSet[_T], key: Callable[[_T], Any]) -> Tuple[_T, ...]: ...
@overload
def order(xs: Tuple[_T, ...], key: Callable[[_T], Any]) -> Tuple[_T, ...]: ...

def size(xs: FrozenSet[Any] | Tuple[Any, ...]) -> int: ...
def astuple(a: Integer, b: Integer) -> IntegerTuple: ...

# Cast helpers: type-level only
def cast_Grid(x: Any) -> Grid: ...
def cast_Object(x: Any) -> Object: ...
def cast_Indices(x: Any) -> Indices: ...
def cast_Patch(x: Any) -> Patch: ...
def cast_Container(x: Any) -> FrozenSet[Any]: ...
def cast_ContainerContainer(x: Any) -> FrozenSet[FrozenSet[Any]]: ...
def cast_Callable(x: Any) -> Callable[..., Any]: ...
def cast_Tuple(x: Any) -> Tuple[Any, ...]: ...
def cast_Integer(x: Any) -> Integer: ...
def cast_IntegerTuple(x: Any) -> IntegerTuple: ...
def cast_Element(x: Any) -> Element: ...
def cast_Piece(x: Any) -> Piece: ...
def cast_IntegerSet(x: Any) -> FrozenSet[Integer]: ...
def cast_Objects(x: Any) -> Objects: ...

# Fallback for everything else; keeps star-imports usable without enumerating all names
def __getattr__(__name: str) -> Any: ...
